name: CI

on: push

permissions:
  contents: read

jobs:
  hlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: "Set up HLint"
        uses: haskell-actions/hlint-setup@fe9cd1cd1af94a23900c06738e73f6ddb092966a

      - name: "Run HLint"
        uses: haskell-actions/hlint-run@eaca4cfbf4a69f4eb875df38b6bc3e1657020378
        with:
          path: '["app/", "src/", "test/"]'
          fail-on: warning

  fourmolu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: "Check formatting with Fourmolu"
        uses: haskell-actions/run-fourmolu@015e6ed9db2b3f344482792d42b7317c764eb30f

  build-binary:
    needs: hlint

    runs-on: ubuntu-latest

    env:
      CONFIG: "--enable-tests --enable-benchmarks"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: haskell-actions/setup@de26526e12bc780fb9d384c1fb61c0bf02e3a40d
        id: setup-haskell-cabal
        with:
          ghc-version: "9.8"
          cabal-version: "latest"

      - name: Update Hackage snapshot
        run: |
          cabal update
          cabal freeze $CONFIG

      - name: Cache dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - name: Build dependencies
        run: cabal build --only-dependencies $CONFIG

      - name: Build application
        run: cabal build $CONFIG all

      - name: Run tests
        run: cabal test $CONFIG all

      - name: Generate documentation
        run: cabal haddock $CONFIG all

      - name: Install binary
        run: cabal install --enable-executable-static --install-method=copy --overwrite-policy=always --installdir=dist/

      - name: Rename binary
        run: mv dist/eselsohr-exe dist/eselsohr

      - name: Store application binary as artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: eselsohr
          path: dist/eselsohr
